# Node parameters for using the timed path follower as local planner with move base. 
# For more information about the move base parameters in this file, please see
#
#  http://www.ros.org/wiki/move_base
#

# Robot Configuration Parameters - Kobuki
max_vel_x: 0.5  # 0.55
min_vel_x: 0.0 

max_vel_y: 0.0  # diff drive robot
min_vel_y: 0.0  # diff drive robot

max_trans_vel: 0.5 # choose slightly less than the base's capability
min_trans_vel: 0.1  # this is the min trans velocity when there is negligible rotational velocity
trans_stopped_vel: 0.1

# Warning!
#   do not set min_trans_vel to 0.0 otherwise dwa will always think translational velocities
#   are non-negligible and small in place rotational velocities will be created.

max_rot_vel: 0.7  # choose slightly less than the base's capability
min_rot_vel: 0.1  # this is the min angular velocity when there is negligible translational velocity
rot_stopped_vel: 0.1
  
acc_lim_x: 1.0 # maximum is theoretically 2.0, but we 
acc_lim_theta: 1.0
acc_lim_y: 0.0      # diff drive robot

# Goal Tolerance Parameters
yaw_goal_tolerance: 0.3  # 0.05
xy_goal_tolerance: 0.15  # 0.10
# latch_xy_goal_tolerance: false


shutdown_costmaps: false

#disable recovery behaviors
recovery_behavior_enabled: false

#controller frequency should be at least 10 Hz to avoid instability
controller_frequency: 20.0
controller_patience: 5.0

#disable oscillation checking
oscillation_timeout: 0.0
oscillation_distance: 0.0

#use path follower as the local planner
base_local_planner: path_executer/PathFollower

#path follower params
PathFollower:
    allow_backwards: false #to allow backwards motion when trying to follow a trajectory. default: false
    xy_goal_tolerance: 0.1 #euclidian goal distance threshold in m. default: 0.1
    yaw_goal_tolerance: 0.2 #rotational goal distance threshold in rad. default: 0.2

#controller gains and velocity bounds for the path follower can be adjusted using dynamic reconfigure (move_base/PathFollower prefix)
